version: "3.1"

Servicios:
  Python:
    construir: ./
    Comando: hello ./app.py

database:

  postgres: 
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: post
      POSTGRES_PASSWORD: post
      POSTGRES_DB: postdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

